[[stack]]
name = "dozzle"
tags = ["auto-start"]
[stack.config]
server = "Local"
repo = "ClementPhan/komodo-stacks"
run_directory = "./stacks/dozzle"
pre_deploy.command = """
sh ../../inject.sh [[OP_CONNECT_TOKEN]]
"""
environment = """
TLD = [[TLD]]
"""
