[[stack]]
name = "immich"
tags = ["auto-start", "auto-stop"]
[stack.config]
server = "Local"
repo = "ClementPhan/komodo-stacks"
run_directory = "./stacks/immich"
env_file_path = "komodo.env"
additional_env_files = [
  { path = ".env", track = true }
]
pre_deploy.command = """
sh ../../inject.sh [[OP_CONNECT_TOKEN]]
"""
environment = """
TLD = [[TLD]]
"""
