[[stack]]
name = "pinchflat"
[stack.config]
server = "outpost"
repo = "ClementPhan/komodo-stacks"
run_directory = "./stacks/pinchflat"
pre_deploy.command = """
sh ../../inject.sh [[OP_CONNECT_TOKEN]]
"""
