[[action]]
name = "Start for backup"
[action.config]
run_at_startup = true
schedule = "Every day at 05:01"
file_contents = """
// Run actions using the pre initialized 'komodo' client.
console.log('Starting all containers...');
const response: Types.Update = await komodo.execute('StartAllContainers', {server: 'Local'});
console.log(response.success);
"""