services:
  gatus:
    image: twinproduction/gatus:v5.36.0@sha256:c5f210d095fa78e6efaa20ffeb14803f2ba4f10615e16a6d12087697149617f0
    restart: always
    # ports:
    #   - "8080:8080"
    environment:
      - TLD=${TLD}
      - MAMMOUTH_IP=${MAMMOUTH_IP}
      - HUB_IP=${HUB_IP}
    volumes:
      - /mnt/software/applications/gatus/data:/data/
      - ./config:/config
      - ${PWD}/lets-encrypt.pem:/etc/ssl/certs/lets-encrypt.pem:ro
    labels:
      traefik.enable: true
      traefik.http.routers.gatus.rule: Host(`gatus.${TLD}`)
      traefik.http.routers.gatus.entrypoints: websecure
      traefik.http.routers.gatus.tls.certresolver: myresolver
      traefik.http.services.gatus.loadbalancer.server.port: 8080
      # Homepage configuration
      homepage.group: Network
      homepage.name: Gatus
      homepage.icon: gatus
      homepage.href: https://gatus.${TLD}/
      homepage.description: Uptime monitor
    networks:
      - traefik_proxy

networks:
  traefik_proxy:
    external: true
    