users:
  ClementPhan: ## Username
    displayname: 'Clément'
    ## WARNING: This is a default password for testing only!
    ## IMPORTANT: Change this password before deploying to production!
    ## Generate a new hash using the instructions at:
    ## https://www.authelia.com/reference/guides/passwords/#passwords
    ## Password is 'authelia'
    password: '{{op://docker/authelia/Users/ClementPhan_digest}}'
    email: '{{op://docker/email/email/email}}'
    groups:
      - 'admin'
      - 'dev'