services:
  op-connect-api:
    container_name: op-connect-api
    image: 1password/connect-api:1.8.2@sha256:e915c0c843972f02b0e7e2de502bda8bd4a092288b3f1866098a857bd715a281
    # ports:
    #   - "8080:8080"
    volumes:
      - "./1password-credentials.json:/home/opuser/.op/1password-credentials.json"
      - "data:/home/opuser/.op/data"
  op-connect-sync:
    image: 1password/connect-sync:1.8.2@sha256:6297ca6136c0f0fb096bc64c49e1bc8df2aab35282ebff8c7bb60745ef176d0d
    # ports:
    #   - "8081:8080"
    volumes:
      - "./1password-credentials.json:/home/opuser/.op/1password-credentials.json"
      - "data:/home/opuser/.op/data"
  op-cli:
    container_name: op-cli
    image: 1password/op:2.35.0@sha256:40f3e68389deee432455f647710ea6947b8cbc0b03f51218e5934c01f3ab73d6
    tty: true # keep container running
    environment:
      - OP_CONNECT_HOST=http://op-connect-api:8080

volumes:
  data:
