services:
  dockerproxy:
    image: ghcr.io/tecnativa/docker-socket-proxy:v0.5.0@sha256:1f5038b54f06c3e18422902cf00ba21803d1c97805aae032e5e6673d532d3459
    container_name: dockerproxy
    environment:
      - CONTAINERS=1 # Allow access to viewing containers
      - SERVICES=1 # Allow access to viewing services (necessary when using Docker Swarm)
      - TASKS=1 # Allow access to viewing tasks (necessary when using Docker Swarm)
      - POST=0 # Disallow any POST operations (effectively read-only)
    # ports:
    #   - 127.0.0.1:2375:2375
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro # Mounted as read-only
    restart: unless-stopped
    networks:
      default: {}

  homepage:
    image: ghcr.io/gethomepage/homepage:v2.2.0@sha256:753eeb0cc22ab7baad39ed47cbd1aae14e193dd1b264e965f193a9ea1d1e1bdd
    container_name: homepage
    user: 0:0
    # ports:
    #   - 3000:3000
    volumes:
      - ${PWD}/config:/app/config # Make sure your local config directory exists
    environment:
      HOMEPAGE_ALLOWED_HOSTS: www.${TLD}  # required, may need port. See gethomepage.dev/installation/#homepage_allowed_hosts
      HOMEPAGE_VAR_TLD: ${TLD} 
    labels:
      traefik.enable: true
      # Router for homepage
      traefik.http.routers.homepage.rule: Host(`www.${TLD}`)
      traefik.http.routers.homepage.entrypoints: websecure
      traefik.http.routers.homepage.tls.certresolver: myresolver
      traefik.http.services.homepage.loadbalancer.server.port: 3000
      # Router for redirection to base domain
      traefik.http.routers.homepage_redirect.rule: HostRegexp(`([a-zA-Z0-9\-]\.)?${TLD}`) || HostRegexp(`([a-zA-Z0-9\-]+\.)?${OLD_TLD}`)
      traefik.http.routers.homepage_redirect.priority: 2
      traefik.http.routers.homepage_redirect.entrypoints: websecure
      traefik.http.routers.homepage_redirect.tls.certresolver: myresolver
      traefik.http.routers.homepage_redirect.tls.domains[0].main: '${TLD}'
      traefik.http.routers.homepage_redirect.tls.domains[1].main: '*.${TLD}'
      traefik.http.routers.homepage_redirect.tls.domains[2].main: '${OLD_TLD}'
      traefik.http.routers.homepage_redirect.tls.domains[3].main: '*.${OLD_TLD}'
      traefik.http.routers.homepage_redirect.middlewares: 'redirection'
      traefik.http.middlewares.redirection.redirectregex.regex: .*
      traefik.http.middlewares.redirection.redirectregex.replacement: https://www.${TLD}
    networks:
      traefik_proxy: {}
      default: {}

networks:
  default: {}
  traefik_proxy:
    external: true
