services:


  adguardhome-sync:
    image: ghcr.io/bakito/adguardhome-sync
    container_name: adguardhome-sync
    command: run --config /config/adguardhome-sync.yaml
    volumes:
      - ${PWD}/sync_config/adguardhome-sync.yaml:/config/adguardhome-sync.yaml
    # ports:
    #   - 8080:8080
    restart: unless-stopped
    labels:
      traefik.enable: true
      traefik.http.routers.adguard-admin.rule: Host(`adguard-sync.${TLD}`)
      traefik.http.routers.adguard-admin.entrypoints: websecure
      traefik.http.routers.adguard-admin.tls.certresolver: myresolver
      traefik.http.services.adguard-admin.loadbalancer.server.port: 8080
      # Homepage configuration
      homepage.group: Network
      homepage.name: Adguard Sync
      homepage.icon: adguard-home
      homepage.href: https://adguard-sync.${TLD}/
      homepage.description: DNS server syncing tool
    networks:
      - traefik_proxy

  adguard:
    image: adguard/adguardhome
    container_name: adguardhome
    restart: unless-stopped
    volumes:
      - /my/own/workdir:/opt/adguardhome/work
      - /my/own/confdir:/opt/adguardhome/conf
    ports:
      - 53:53/tcp
      - 53:53/udp
      # - 80:80/tcp
      # - 443:443/tcp
      # - 443:443/udp
      # - 3000:3000/tcp
      - 853:853/tcp # DNS-over-TLS
      - 853:853/udp # DNS-over-QUIC
      # - 6060:6060/tcp # Debuging
    labels:
      traefik.enable: true
      # Admin panel configuration
      traefik.http.routers.adguard-admin.rule: Host(`adguard.${TLD}`)
      traefik.http.routers.adguard-admin.entrypoints: websecure
      traefik.http.routers.adguard-admin.tls.certresolver: myresolver
      traefik.http.services.adguard-admin.loadbalancer.server.port: 3000
      # DNS over https
      traefik.http.routers.adguard-dns-https.rule: Host(`dns01.${TLD}`)
      traefik.http.routers.adguard-dns-https.entrypoints: websecure
      traefik.http.routers.adguard-dns-https.tls.certresolver: myresolver
      traefik.http.services.adguard-dns-https.loadbalancer.server.port: 80
      # DNS over TLS
      traefik.tcp.routers.adguard-dns_tls.rule: HostSNI(`dns01.${TLD}`) # change with your own domain/sub domain
      traefik.tcp.routers.adguard-dns_tls.entrypoints: dns_over_tls
      traefik.tcp.routers.adguard-dns_tls.tls.certresolver: letsencrypt
      traefik.tcp.services.adguard-dns_tls.loadbalancer.server.port: 53
      # Homepage configuration
      homepage.group: Network
      homepage.name: Adguard Home
      homepage.icon: adguard-home
      homepage.href: https://adguard.${TLD}/
      homepage.description: DNS server and filtering
    networks:
      - traefik_proxy

networks:
  traefik_proxy:
    external: true
    