# Anchors for default conditions and tests
default-conditions: &conditions
  conditions:
    - "[STATUS] == 200"
    - "[CERTIFICATE_EXPIRATION] > 48h"

adguard-dns-test: &dns-test
  dns:
    query-name: "healthcheck.adguardhome.test."
    query-type: "A"
  conditions:
    - "[DNS_RCODE] == NOERROR"

ignore-redirections: &ignore-redirect
  client:
    ignore-redirect: true

# Storage configuration
storage:
  type: sqlite
  path: /data/data.db

# Alerting configuration
alerting:
  pushover:
    user-key: "${PUSHOVER_USER_KEY}"
    application-token: "${PUSHOVER_APP_TOKEN}"
    priority: -1
    default-alert:
      send-on-resolved: true
      failure-threshold: 2
      success-threshold: 2
  github:
    repository-url: "https://github.com/ClementPhan/homelab-issues"
    token: "${GITHUB_TOKEN}"
    default-alert:
      send-on-resolved: true
      failure-threshold: 2
      success-threshold: 2

default-alerts: &alerts
  alerts:
    - type: pushover
    - type: github

# Maintenance configuration
maintenance:
  start: 04:58
  duration: 5m
  timezone: "Europe/Paris"

# Endpoints to monitor
endpoints:
  # DNS
  - name: DNS on Hub
    group: DNS
    url: "${HUB_IP}" # Address of the DNS server to use
    <<: [*dns-test, *alerts]

  - name: DNS on Mammouth
    group: DNS
    url: "${MAMMOUTH_IP}" # Address of the DNS server to use
    <<: [*dns-test, *alerts]

  # Administration
  - name: Komodo
    group: Administration
    url: "https://komodo.${TLD}"
    <<: [*conditions, *alerts, *ignore-redirect]

  - name: idrac
    group: Administration
    url: "https://idrac.${TLD}/login.html"
    interval: 5m
    <<: [*conditions, *alerts, *ignore-redirect]

  - name: Dozzle
    group: Administration
    url: "https://dozzle.${TLD}/healthcheck"
    <<: [*conditions, *alerts, *ignore-redirect]

  # Network and infrastructure
  - name: Box
    group: Network
    url: "http://box.${TLD}"
    conditions:
      - "[STATUS] == 200"
    <<: [*alerts, *ignore-redirect]

  - name: Traefik
    group: Network
    url: "https://traefik.${TLD}/api/version"
    conditions:
      - "[STATUS] == 200"
      - "[CERTIFICATE_EXPIRATION] > 48h"
      - "has([BODY].Version) == true"
    <<: [*alerts, *ignore-redirect]

  # Devices
  - name: Gul
    group: Devices
    url: "https://gul.${TLD}"
    <<: [*conditions, *alerts, *ignore-redirect]

  - name: PeaNUT
    group: Devices
    url: "https://peanut.${TLD}/api/ping"
    conditions:
      - "[STATUS] == 200"
      - "[CERTIFICATE_EXPIRATION] > 48h"
      - '[BODY] == "pong"'
    <<: [*alerts, *ignore-redirect]

  - name: Home Assistant
    group: Devices
    url: "https://hub.${TLD}/api/"
    headers:
      Authorization: "Bearer ${HASS_TOKEN}"
    conditions:
      - "[STATUS] == 200"
      - "[CERTIFICATE_EXPIRATION] > 48h"
      - "[BODY].message == API running."
    <<: [*alerts, *ignore-redirect]

  # Containers and services
  - name: Pocket ID
    group: Services
    url: "https://pocketid.${TLD}/healthz"
    conditions:
      - "[CERTIFICATE_EXPIRATION] > 48h"
      - "[STATUS] == 204"
    <<: [*alerts, *ignore-redirect]

  - name: AdGuard on Mammouth
    group: Services
    url: "https://adguard.${TLD}/login.html"
    <<: [*conditions, *alerts, *ignore-redirect]

  - name: AdGuard on Hub
    group: Services
    url: "https://hub.${TLD}:3000"
    conditions:
      - "[STATUS] == 401"
      - "[CERTIFICATE_EXPIRATION] > 48h"
    <<: [*alerts, *ignore-redirect]

  - name: AdGuard Sync
    group: Services
    url: "https://adguard-sync.${TLD}"
    <<: [*conditions, *alerts, *ignore-redirect]
