storage:
  type: sqlite
  path: /data/data.db

endpoints:
  - name: Komodo
    group: core
    url: "https://komodo.${TLD}"
    conditions:
      - "[STATUS] == 200"
      - "[CERTIFICATE_EXPIRATION] > 48h"

  - name: idrac
    group: internal
    url: "https://idrac.${TLD}"
    conditions:
      - "[STATUS] == 200"
      - "[CERTIFICATE_EXPIRATION] > 48h"

  - name: Gul
    group: internal
    url: "https://gul.${TLD}"
    conditions:
      - "[STATUS] == 200"
      - "[CERTIFICATE_EXPIRATION] > 48h"

  - name: Box
    group: Network
    url: "http://box.${TLD}"
    conditions:
      - "[STATUS] == 200"

  - name: PeaNUT
    group: Network
    url: "http://peanut.${TLD}/api/ping"
    conditions:
      - "[STATUS] == 200"
      - "[CERTIFICATE_EXPIRATION] > 48h"
      - "[BODY] == \"pong\""

  - name: Pocket ID
    group: Network
    url: "http://pocketid.${TLD}/healthz"
    conditions:
      - "[STATUS] == 204"
      - "[CERTIFICATE_EXPIRATION] > 48h"

  - name: Traefik
    group: Network
    url: "http://traefik.${TLD}/api/version"
    conditions:
      - "[STATUS] == 200"
      - "[CERTIFICATE_EXPIRATION] > 48h"
      - "has([BODY].Version) == true"

  - name: Dozzle
    group: Administration
    url: "http://dozzle.${TLD}/healthcheck"
    conditions:
      - "[STATUS] == 200"
      - "[CERTIFICATE_EXPIRATION] > 48h"

  - name: AdGuard Dashboard on Mammouth
    group: Network
    url: "https://adguard.${TLD}"
    conditions:
      - "[STATUS] == 200"
      - "[CERTIFICATE_EXPIRATION] > 48h"

  - name: AdGuard DNS Service on Mammouth
    group: Network
    url: "${MAMMOUTH_IP}" # Address of the DNS server to use
    dns:
      query-name: "healthcheck.adguardhome.test."
      query-type: "A"
    conditions:
      - "[DNS_RCODE] == NODATA"

  - name: AdGuard Dashboard on Hub
    group: Network
    url: "https://hub.${TLD}:3000"
    conditions:
      - "[STATUS] == 400"
      - "[CERTIFICATE_EXPIRATION] > 48h"

  - name: AdGuard DNS Service on Hub
    group: Network
    url: "${HUB_IP}" # Address of the DNS server to use
    dns:
      query-name: "healthcheck.adguardhome.test."
      query-type: "A"
    conditions:
      - "[DNS_RCODE] == NOERROR"
      - "BODY == 1.1.1.1"

  - name: AdGuard Sync
    group: Network
    url: "http://adguard-sync.${TLD}"
    conditions:
      - "[STATUS] == 200"
      - "[CERTIFICATE_EXPIRATION] > 48h"
