default-conditions: &conditions
  conditions:
    - "[STATUS] == 200"
    - "[CERTIFICATE_EXPIRATION] > 48h"

adguard-dns-conditions: &dns-conditions
  dns:
    query-name: "healthcheck.adguardhome.test."
    query-type: "A"
  conditions:
    - "[DNS_RCODE] == NOERROR"

storage:
  type: sqlite
  path: /data/data.db

endpoints:
  - name: Komodo
    group: core
    url: "https://komodo.${TLD}"
    <<: *conditions

  - name: idrac
    group: internal
    url: "https://idrac.${TLD}"
    <<: *conditions

  - name: Gul
    group: internal
    url: "https://gul.${TLD}"
    <<: *conditions

  - name: Box
    group: Network
    url: "http://box.${TLD}"
    conditions:
      - "[STATUS] == 200"

  - name: PeaNUT
    group: Network
    url: "http://peanut.${TLD}/api/ping"
    <<: *conditions
    conditions:
      - '[BODY] == "pong"'

  - name: Pocket ID
    group: Network
    url: "http://pocketid.${TLD}/healthz"
    <<: *conditions
    conditions:
      - "[STATUS] == 204"

  - name: Traefik
    group: Network
    url: "http://traefik.${TLD}/api/version"
    <<: *conditions
    conditions:
      - "has([BODY].Version) == true"

  - name: Dozzle
    group: Administration
    url: "http://dozzle.${TLD}/healthcheck"
    <<: *conditions

  - name: AdGuard Dashboard on Mammouth
    group: Network
    url: "https://adguard.${TLD}"
    <<: *conditions

  - name: AdGuard DNS Service on Mammouth
    group: Network
    url: "${MAMMOUTH_IP}" # Address of the DNS server to use
    <<: *dns-conditions

  - name: AdGuard Dashboard on Hub
    group: Network
    url: "https://hub.${TLD}:3000"
    <<: *conditions
    conditions:
      - "[STATUS] == 401"

  - name: AdGuard DNS Service on Hub
    group: Network
    url: "${HUB_IP}" # Address of the DNS server to use
    <<: *dns-conditions

  - name: AdGuard Sync
    group: Network
    url: "http://adguard-sync.${TLD}"
    <<: *conditions

  - name: Home Assistant
    group: Network
    url: "http://hub.${TLD}/api/"
    headers:
      Authorization: "Bearer ${HASS_TOKEN}"
    <<: *conditions
    conditions:
      - '[BODY].message == "API running."'