http:
  # Add the router
  routers:
    komodo:
      entryPoints: websecure
      service: komodo
      rule: Host(`komodo.{{ env "TLD" }}`)
      tls:
        certresolver: myresolver

    # Add the webhook router
    komodo_webhooks:
      entryPoints: ext_websecure
      service: komodo
      rule: Host(`komodo.external.{{ env "TLD" }}`) && PathPrefix(`/listener`)
      tls:
        certresolver: myresolver

  # Add the service
  services:
    komodo:
      loadBalancer:
        servers:
          - url: http://services.mammouth.{{ env "TLD" }}:30160
