services:
  handbrake:
    image: jlesage/handbrake:v26.07.1@sha256:682eaf62bdf75e9e19003cf46892a452e29af3bce28c1321e7639255cc3fbce1
    container_name: handbrake
    deploy:
      resources:
        limits:
          cpus: '14'
    # ports:
    #   - 5800:5800/tcp
    volumes:
      - ./storage:/storage:ro
      - /mnt/software/applications/handbrake/config:/config
      - /mnt/bulk/media/video/ingress/BR_1K_DVD:/watch
      - /mnt/bulk/media/video/ingress/BR_2K:/watch2
      - /mnt/bulk/media/video/ingress/BR_4K:/watch3
      - /mnt/bulk/media/video/series:/output/series
      - /mnt/bulk/media/video/films:/output/films
    restart: 'unless-stopped'
    # Optional - alternative address used for autodiscovery
    environment:
      - TZ=Europe/Paris
      - KEEP_APP_RUNNING=1
      - AUTOMATED_CONVERSION_OUTPUT_SUBDIR=SAME_AS_SRC
      - AUTOMATED_CONVERSION_PRESET=My Persets/BR_1K_DVD
      - AUTOMATED_CONVERSION_FORMAT=mkv
      - AUTOMATED_CONVERSION_KEEP_SOURCE=0
      - AUTOMATED_CONVERSION_NON_VIDEO_FILE_ACTION=copy
    labels:
      # Traefik configuration
      traefik.enable: true
      traefik.http.routers.handbrake.rule: Host(`handbrake.${TLD}`)
      traefik.http.routers.handbrake.entrypoints: websecure
      traefik.http.routers.handbrake.tls.certresolver: myresolver
      traefik.http.services.handbrake.loadbalancer.server.port: 5800
      docker-volume-backup.stop-during-backup: true
      # Homepage configuration
      homepage.group: Media & Data
      homepage.name: HandBrake
      homepage.icon: handbrake
      homepage.href: https://handbrake.${TLD}/
      homepage.description: Video transcoder
    networks:
      traefik_proxy: {}

networks:
  traefik_proxy:
    external: true
