services:
  traefik:
    image: traefik:v3.6.12@sha256:171c9c3565b29f6c133f1c1b43c5d4e5853415198e9e1078c001f8702ff66aec
    container_name: "traefik"
    restart: always
    ports:
      - {{op://docker/TrueNas/config/services_ip}}:80:80
      - {{op://docker/TrueNas/config/services_ip}}:443:443
      - {{op://docker/TrueNas/config/services_ip}}:9080:9080
      - {{op://docker/TrueNas/config/services_ip}}:9443:9443
    environment:
      - OVH_ENDPOINT=op://docker/ovh/server/endpoint
      - OVH_APPLICATION_KEY=op://docker/ovh/secrets/app_key
      - OVH_APPLICATION_SECRET=op://docker/ovh/secrets/app_secret
      - OVH_CONSUMER_KEY=op://docker/ovh/secrets/consumer_key
      - TRAEFIK_CERTIFICATESRESOLVERS_MYRESOLVER_ACME_EMAIL=op://docker/email/email/email
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./config/:/etc/traefik/:ro
      - letsencrypt:/letsencrypt
    labels:
      traefik.enable: true
      traefik.http.routers.traefik.rule: Host(`traefik.{{op://docker/home_address/url/url}}`)
      traefik.http.routers.traefik.entrypoints: websecure
      traefik.http.routers.traefik.tls.certresolver: myresolver
      traefik.http.services.traefik.loadbalancer.server.port: 8080
      # Homepage configuration
      homepage.group: Network
      homepage.name: Traefik
      homepage.icon: traefik.svg
      homepage.href: https://traefik.{{op://docker/home_address/url/url}}/
      homepage.description: Local reverse proxy
    networks:
      authelia: {}
      traefik_proxy:
        ipv4_address: 10.0.1.200

  authelia:
    image: 'authelia/authelia:4.38'
    container_name: 'authelia'
    volumes:
      - './authelia/secrets:/secrets:ro'
      - './authelia/config:/config'
      - './authelia/logs:/var/log/authelia/'
    networks:
      authelia: {}
    labels:
      ## Expose Authelia through Traefik
      traefik.enable: true
      traefik.docker.network: authelia
      traefik.http.routers.authelia.rule: Host(`auth.{{op://docker/home_address/url/url}}`)
      traefik.http.routers.authelia.entrypoints: websecure
      traefik.http.routers.authelia.tls.certresolver: myresolver
      ## Setup Authelia ForwardAuth Middlewares
      traefik.http.middlewares.authelia.forwardAuth.address: 'https://authelia:9091/api/authz/forward-auth'
      traefik.http.middlewares.authelia.forwardAuth.trustForwardHeader: 'true'
      traefik.http.middlewares.authelia.forwardAuth.authResponseHeaders: 'Remote-User,Remote-Groups,Remote-Name,Remote-Email'
    environment:
      TZ: 'Europe/Paris'
      X_AUTHELIA_CONFIG_FILTERS: 'template'
  
  whoami-secure:
    image: 'traefik/whoami'
    restart: 'unless-stopped'
    container_name: 'whoami-secure'
    labels:
      traefik.enable: 'true'
      traefik.http.routers.whoami-secure.rule: 'Host(`whoami-secure.{{op://docker/home_address/url/url}}`)'
      traefik.http.routers.whoami-secure.entrypoints: websecure
      traefik.http.routers.whoami-secure.middlewares: 'authelia@docker'
    networks:
      traefik_proxy: {}

volumes:
  letsencrypt: null

networks:
  authelia:
    driver: bridge
  traefik_proxy:
    name: traefik_proxy
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.1.0/24
          gateway: 10.0.1.1
