services:
  bichon:
    image: rustmailer/bichon:0.3.7
    container_name: bichon
    # ports:
    #   - "15630:15630"
    volumes:
      - /mnt/software/applications/bichon/data:/data
    user: "0:0"
    environment:
      BICHON_ROOT_DIR: /data
      BICHON_LOG_LEVEL: info
      BICHON_CORS_ORIGINS: https://bichon.{{op://docker/home_address/url/url}}
    restart: always
    labels:
      traefik.enable: true
      traefik.http.routers.bichon.rule: Host(`bichon.{{op://docker/home_address/url/url}}`)
      traefik.http.routers.bichon.entrypoints: websecure
      traefik.http.routers.bichon.tls.certresolver: myresolver
      traefik.http.services.bichon.loadbalancer.server.port: 15630
      # Homepage configuration
      homepage.group: Home Management
      homepage.name: Bichon
      homepage.icon: bichon.svg
      homepage.href: https://bichon.{{op://docker/home_address/url/url}}/
      homepage.description: Email Archiving
    networks:
      traefik_proxy: null

networks:
  traefik_proxy:
    external: true