name: audiobookshelf

services:
  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:2.34.0@sha256:4143292c530f6ac6700afd13360c04f477e4f1a81c1c97c4224b1c7e4330c5c4 
    # ports:
    #   - 13378:80
    volumes:
      - /mnt/bulk/media/audio/audiobooks:/audiobooks
      - /mnt/bulk/media/audio/podcasts:/podcasts
      - /mnt/software/applications/audiobookshelf/config:/config
      - /mnt/software/applications/audiobookshelf/metadata:/metadata
    environment:
      - TZ=Europe/Paris
    restart: always
    labels:
      traefik.enable: true
      traefik.http.routers.audiobookshelf.rule: Host(`audiobookshelf.${TLD}`)
      traefik.http.routers.audiobookshelf.entrypoints: websecure
      traefik.http.routers.audiobookshelf.tls.certresolver: myresolver
      traefik.http.services.audiobookshelf.loadbalancer.server.port: 80
      # Homepage configuration
      homepage.group: Media & Data
      homepage.name: Audiobookshelf
      homepage.icon: audiobookshelf.svg
      homepage.href: https://audiobookshelf.${TLD}/
      homepage.description: Audiobook and podcast repository
    networks:
      traefik_proxy: {}
    
  libation:
    image: rmcrackan/libation:13.4.2@sha256:0544f061512f2c272a153a2d6d4b3cedc276486949808a5e3acd8842dc3cc4c4
    restart: always
    user: 0:0
    volumes:
      - ${PWD}/config:/config
      - /mnt/bulk/media/audio/audiobooks/libation:/data
      - /mnt/software/applications/audiobookshelf/libation_db:/db
    environment:
      - SLEEP_TIME=177h

networks:
  traefik_proxy:
    external: true
      