name: audiobookshelf

services:
  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:2.33.2@sha256:a44ed89b3e845faa1f7d353f2cc89b2fcd8011737dd14075fa963cf9468da3a5 
    # ports:
    #   - 13378:80
    volumes:
      - /mnt/bulk/media/audio/audiobooks:/audiobooks
      - /mnt/bulk/media/audio/podcasts:/podcasts
      - /mnt/software/applications/audiobookshelf/config:/config
      - /mnt/software/applications/audiobookshelf/metadata:/metadata
    environment:
      - TZ=Europe/Paris
    restart: always
    labels:
      traefik.enable: true
      traefik.http.routers.audiobookshelf.rule: Host(`audiobookshelf.{{op://docker/home_address/url/url}}`)
      traefik.http.routers.audiobookshelf.entrypoints: websecure
      traefik.http.routers.audiobookshelf.tls.certresolver: myresolver
      traefik.http.services.audiobookshelf.loadbalancer.server.port: 80
      # Homepage configuration
      homepage.group: Media & Data
      homepage.name: Audiobookshelf
      homepage.icon: audiobookshelf.svg
      homepage.href: https://audiobookshelf.{{op://docker/home_address/url/url}}/
      homepage.description: Audiobook and podcast repository
      homepage.widget.type: audiobookshelf
      homepage.widget.url: https://audiobookshelf.{{op://docker/home_address/url/url}}
      homepage.widget.key: {{op://docker/audiobookshelf/api/key}}
    networks:
      traefik_proxy: {}
    
  libation:
    image: rmcrackan/libation:13.3.5@sha256:fcfeaa406a3567e3de89d85bf761d17868029c6e8a127922672770cb812b9be8
    restart: always
    user: 0:0
    volumes:
      - ${PWD}/config:/config
      - /mnt/bulk/media/audio/audiobooks/libation:/data
      - /mnt/software/applications/audiobookshelf/libation_db:/db
    environment:
      - SLEEP_TIME=177h

networks:
  traefik_proxy:
    external: true
      