name: audiobookshelf

services:
  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:2.35.1@sha256:1eef6716183c52abafe5405e7d6be8390248ecd59c7488c44af871757ac8fc4d 
    # ports:
    #   - 13378:80
    volumes:
      - /mnt/bulk/media/audio/audiobooks:/audiobooks
      - /mnt/bulk/media/audio/podcasts:/podcasts
      - /mnt/software/applications/audiobookshelf/config:/config
      - /mnt/software/applications/audiobookshelf/metadata:/metadata
    environment:
      - TZ=Europe/Paris
    restart: always
    labels:
      traefik.enable: true
      traefik.http.routers.audiobookshelf.rule: Host(`audiobookshelf.${TLD}`)
      traefik.http.routers.audiobookshelf.entrypoints: websecure
      traefik.http.routers.audiobookshelf.tls.certresolver: myresolver
      traefik.http.services.audiobookshelf.loadbalancer.server.port: 80
      # Homepage configuration
      homepage.group: Media & Data
      homepage.name: Audiobookshelf
      homepage.icon: audiobookshelf.svg
      homepage.href: https://audiobookshelf.${TLD}/
      homepage.description: Audiobook and podcast repository
    networks:
      traefik_proxy: {}
    
  libation:
    image: rmcrackan/libation:13.4.9@sha256:52b554cd4da0e0562779374acdd53974045bd9b10c5513e966ca25c4a35e690f
    restart: always
    user: 0:0
    volumes:
      - ${PWD}/config:/config
      - /mnt/bulk/media/audio/audiobooks/libation:/data
      - /mnt/software/applications/audiobookshelf/libation_db:/db
    environment:
      - SLEEP_TIME=177h

networks:
  traefik_proxy:
    external: true
      