services:
  peanut:
    image: brandawg93/peanut:6.0.0@sha256:6629dce915da8b313f08b2e73dd2e54b60e7c0f642c21a8ebc37fe0a820bf41e
    container_name: PeaNUT
    restart: unless-stopped
    user: {{op://docker/TrueNas/unpriviledged_user/uid}}:{{op://docker/TrueNas/unpriviledged_user/gid}} # should be owner of volumes
    volumes:
      - /mnt/software/applications/peanut/config:/config
      - /mnt/software/applications/peanut/app_config:/app/config
    # ports:
    #   - 8080:8080
    environment:
      - WEB_PORT=8080
      - WEB_USERNAME={{op://docker/peanut/username}}
      - WEB_PASSWORD={{op://docker/peanut/password}}
      - DEBUG=true
    labels:
      # Traefik configuration
      traefik.enable: true
      traefik.http.routers.peanut.rule: Host(`peanut.${TLD}`)
      traefik.http.routers.peanut.entrypoints: websecure
      traefik.http.routers.peanut.tls.certresolver: myresolver
      traefik.http.services.peanut.loadbalancer.server.port: 8080
      docker-volume-backup.stop-during-backup: true
      # Homepage configuration
      homepage.group: Network
      homepage.name: PeaNUT
      homepage.icon: peanut.svg
      homepage.href: https://peanut.${TLD}/
      homepage.description: UPS status
    networks:
      traefik_proxy: {}

networks:
  traefik_proxy:
    external: true
