services:
  actual:
    image: ghcr.io/actualbudget/actual:26.2.1@sha256:ea21a0b6243797d35ef6c4a8713c87efaba8fec3b3663220fa3af61f352fba5e
    restart: always
    # ports:
    #   - '5006:5006'
    volumes:
      - /mnt/software/applications/actual/data:/data
    healthcheck:
      # Enable health check for the instance
      test: ['CMD-SHELL', 'node src/scripts/health-check.js']
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 20s
    labels:
      # Traefik configuration
      traefik.enable: true
      traefik.http.routers.actual.rule: Host(`actual.{{op://docker/home_address/url/url}}`)
      traefik.http.routers.actual.entrypoints: websecure
      traefik.http.routers.actual.tls.certresolver: myresolver
      traefik.http.services.actual.loadbalancer.server.port: 5006
      # Homepage configuration
      homepage.group: Home Management
      homepage.name: Actual Budget
      homepage.icon: actual-budget.svg
      homepage.href: https://actual.{{op://docker/home_address/url/url}}/
      homepage.description: Budget management
    networks:
      traefik_proxy: {}

volumes:
  config: null

networks:
  traefik_proxy:
    external: true